version: '2'
services:
  starter-bundle:
    build:
      context: ..
      dockerfile: .buildkite/Dockerfile
    environment:
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_URL
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BUILD_CREATOR
      - BUILDKITE_COMMIT
      - BUILDKITE_JOB_ID
      - CODECLIMATE_REPO_TOKEN
    working_dir: /home/starter-bundle
    volumes:
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - /tmp/.vault_pass:/root/.vault_pass
      - ..:/home/starter-bundle
